apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    template: cronjob-prune-projects
  name: system:project-pruners
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.job_service_account }}
userNames:
- system:serviceaccount:{{ .Values.namespace }}:{{ .Values.job_service_account }}
