{{- if .Values.generateSecret }}
apiVersion: v1
stringData:
  GITLAB_PERSONAL_ACCESS_TOKEN: {{ .Values.env.secret.personalAccessToken }}
kind: Secret
metadata:
  name: {{ .Values.env.secret.name }}
type: Opaque
{{- end }}
