apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: ldap-group-syncer
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
  - create
  - update
